### ISSUE TITLE
getting TIMEOUT

### ISSUE THREAD

**Issue by djl314** [jlongua/plan9-dns#6]
newbie here...

all Plan9 servers keep getting TIMEOUT 

running dnscrypt 2.15

Loaded w/
 ## Open NIC Servers( Frank Denis)
 [sources.'opennic'] 
  urls = ['https://download.dnscrypt.info/dnscrypt-resolvers/v3/opennic.md' ]
  cache_file = 'opennic.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

:Filters

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = false

# Do not use servers implementing the Oblivious DoH protocol
odoh_servers = false

# Server must support DNS security extensions (DNSSEC)
require_dnssec = true

# Server must not log user queries (declarative)
require_nolog = false

# Server must not enforce its own blacklist (for parental control, ads blocking...)
require_nofilter = true

**Comment by jlongua** [comment]
The abuse I am seeing is hundreds of fin_wait1 from individual ip's and thousands of conntrack connections from individual ip's. Iran is the source of 99.9% of the abuse. I have mitigations in place for now, but will probably end up geoblocking Iran in the future.
